CC=clang++
CFLAGS=-Wall -pedantic
LDFLAGS=
SOURCES=bicycle_tester.cpp bicycle.cpp
EXECUTABLE=output

all:
	$(CC) $(CFLAGS) $(SOURCES) -g -o $(EXECUTABLE)

prod:
	$(CC) $(CFLAGS) $(SOURCES) -o $(EXECUTABLE)

