CC=clang++
CFLAGS=-Wall -pedantic
LDFLAGS=
SOURCES=clock_tester.cpp clock.cpp
EXECUTABLE=output

all:
	$(CC) $(CFLAGS) $(SOURCES) -g -o $(EXECUTABLE)

prod:
	$(CC) $(CFLAGS) $(SOURCES) -o $(EXECUTABLE)

