CC=clang++
CFLAGS=-Wall -pedantic
LDFLAGS=
SOURCES=measurement_list.cpp test.cpp
EXECUTABLE=test

all:
	$(CC) $(CFLAGS) $(SOURCES) -g -o $(EXECUTABLE)

prod:
	$(CC) $(CFLAGS) $(SOURCES) -o $(EXECUTABLE)

