CC=clang++
CFLAGS=-Wall -pedantic
LDFLAGS=
SOURCES=decryption.cpp test-decryption.cpp
EXECUTABLE=output

all:
	$(CC) $(CFLAGS) $(SOURCES) -o $(EXECUTABLE)

debug:
	$(CC) $(CFLAGS) $(SOURCES) -g -o $(EXECUTABLE)

